// This file is auto-generated by scripts/generate-route-stub.cjs
// It provides a minimal routeTree export so TypeScript and CI builds
// that require a generated route tree succeed. Replace with a proper
// generated file from your route generator when available.

export const routeTree: any = {}
